name: viewer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  rinf: ^6.6.2
  provider: ^6.0.1
  file_picker: ^6.2.0
  window_manager: ^0.3.8
  desktop_drop: ^0.4.4
  sidebarx: ^0.16.2
  flutter:
    sdk: flutter
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
